Universities = [
    "University of Aberdeen",
    "University of Abertay Dundee",
    "Aberystwyth University",
    "Anglia Ruskin University",
    "The Arts University Bournemouth",
    "University of the Arts London",
    "Aston University",
    "Bangor University",
    "University of Bath",
    "Bath Spa University",
    "University of Bedfordshire",
    "University of Birmingham",
    "Birmingham City University",
    "University College Birmingham",
    "Bishop Grosseteste University",
    "University Centre at Blackburn College",
    "University of Bolton",
    "Bournemouth University",
    "BPP University College of Professional Studies",
    "University of Bradford",
    "University of Brighton",
    "Brighton and Sussex Medical School",
    "University of Bristol",
    "Brunel University",
    "University of Buckingham",
    "Buckinghamshire New University",
    "University of Cambridge",
    "Canterbury Christ Church University",
    "Cardiff University",
    "Cardiff Metropolitan University (UWIC)",
    "University of Central Lancashire",
    "University of Chester",
    "University of Chichester",
    "City University London",
    "Coventry University",
    "Cranfield University",
    "University for the Creative Arts",
    "University of Cumbria",
    "De Montfort University",
    "University of Derby",
    "University of Dundee",
    "Durham University",
    "University of East Anglia",
    "University of East London",
    "University of East London School of Law",
    "Edge Hill University",
    "University of Edinburgh",
    "Edinburgh Napier University",
    "University of Essex",
    "University of Exeter",
    "Falmouth University",
    "University of Glasgow",
    "Glasgow Caledonian University",
    "University of Gloucestershire",
    "University of Greenwich",
    "Glyndwr University",
    "Harper Adams University",
    "Heriot-Watt University",
    "University of Hertfordshire",
    "University of the Highlands & Islands",
    "University of Huddersfield",
    "University of Hull",
    "Hull York Medical School (HYMS)",
    "Imperial College London",
    "Keele University",
    "University of Kent",
    "Kingston University",
    "Lancaster University",
    "University of Leeds",
    "Leeds Metropolitan University",
    "Leeds Trinity University",
    "University of Leicester",
    "University of Lincoln",
    "University of Liverpool",
    "Liverpool Hope University",
    "Liverpool John Moores University",
    "University of London",
    "University College London (UCL)",
    "London Metropolitan University",
    "London South Bank University",
    "Loughborough University",
    "University of Manchester",
    "Manchester Metropolitan University",
    "Middlesex University",
    "Newcastle University",
    "Newman University",
    "University of Northampton",
    "Northumbria University",
    "Norwich University of the Arts",
    "University of Nottingham",
    "Nottingham Trent University",
    "The Open University",
    "University of Oxford",
    "Oxford Brookes University",
    "University of Plymouth",
    "University of Portsmouth",
    "Queen's University Belfast",
    "Queen Margaret University",
    "University of Reading",
    "The Robert Gordon University",
    "Roehampton University",
    "Royal Agricultural University",
    "Royal College of Art",
    "University of St Andrews",
    "University of St Mark & St John",
    "University of Salford",
    "University of Sheffield",
    "Sheffield Hallam University",
    "University of Southampton",
    "Southampton Solent University",
    "University of South Wales",
    "Staffordshire University",
    "University of Stirling",
    "University of Strathclyde",
    "University of Strathclyde",
    "University of Sunderland",
    "University of Surrey",
    "University of Sussex",
    "Swansea Metropolitan University",
    "Swansea University",
    "Teesside University",
    "University of Ulster",
    "University of Wales",
    "University of Warwick",
    "University of West London",
    "University of Westminster",
    "University of the West of England",
    "University of the West of Scotland",
    "University of Winchester",
    "University of Wolverhampton",
    "University of Worcester",
    "University of York",
    "York St John University"
    ]
